# Generated by Django 4.0.3 on 2022-04-15 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankingSolutuon', '0002_credit_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credit',
            name='address',
        ),
    ]
